spring:
    application:
        name: volante

    datasource:
        url: jdbc:mariadb://localhost:3306/test1
        username: root
        password: password
        hikari:
            maximum-pool-size: 10
    
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MariaDBDialect
        show-sql: true   # SQL出力が欲しい場合
    # HikariCPコネクションプールの設定（任意）

logging:
    level:
        root: INFO
        '[jp.co.volante]': DEBUG  # パッケージごとに設定可能